### ISSUE TITLE
Error with compiledb-gen-make when no exclude flags specified

### ISSUE THREAD

**Issue by bartlibert** [nickdiego/compiledb-generator#21]
When I run compiledb-gen-make without any exclude flags, the program crashes:

```
## Processing build commands from 'std input'
Traceback (most recent call last):
  File "/home/bart/Tech/code/follow/compiledb-generator/compiledb-gen-parser", line 239, in <module>
    sys.exit(main())
  File "/home/bart/Tech/code/follow/compiledb-generator/compiledb-gen-parser", line 59, in main
    (count, skipped, compile_db) = parse_flags(build_log, proj_dir, include_path_prefix, exclude_list, verbose)
  File "/home/bart/Tech/code/follow/compiledb-generator/compiledb-gen-parser", line 103, in parse_flags
    msg('Error: Regular expression not valid: {}'.format(regex_pattern))
UnboundLocalError: local variable 'regex_pattern' referenced before assignment

```
The following does work (i.e. an empty exclude list)
```
compiledb-gen-make -- -e " "
```

**Comment by nickdiego** [comment]
Thanks for reporting.
Could you please retest it?

PS: I'm gonna add unit tests/CI soon.

**Comment by bartlibert** [comment]
Works as expected now, thanks for the quick fix!
