### ISSUE TITLE
TypeError with a project

### ISSUE THREAD

**Issue by hameerabbasi** [nickdiego/compiledb-generator#50]
`compiledb` fails with xnd-all. Steps to reproduce:

```bash
git clone https://github.com/plures/xnd-all.git
cd xnd-all
compiledb -n make install
```

Output:
```
## Processing build commands from 3
## Loaded compilation database with 36 entries from compile_commands.json
## Writing compilation database with 36 entries to compile_commands.json
## Done.
Traceback (most recent call last):
  File "/usr/local/bin/compiledb", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/compiledb/commands/make.py", line 103, in command
    pipe.wait()
  File "/usr/local/lib/python3.7/site-packages/compiledb/commands/make.py", line 63, in __exit__
    self.cleanup()
  File "/usr/local/lib/python3.7/site-packages/compiledb/commands/make.py", line 68, in cleanup
    if os.path.isfile(self.path):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by nickdiego** [comment]
Thanks for reporting this.
I'll check it now :)

**Comment by nickdiego** [comment]
@hameerabbasi 
Could you please retest it.

**Comment by hameerabbasi** [comment]
Yes, but it isn't detecting all the files.

```bash
make install | grep 'gcc' | wc -l
      87
```

Whereas `compiledb -n make install` produces just 36. The project uses autotools.

**Comment by nickdiego** [comment]
It looks like each file is build twice. Run the following cmd:
```sh
make -Bnk | grep 'gcc.* -c'
```
Currently, `compiledb` try to keep only one entry per source file in the final compilation database (I'm quite sure to remember someone reporting issues in tools using compdb with duplicated compilation commands for the same file).

Have you tried to use the `compile_commands.json` generated with some specific tool?

**Comment by hameerabbasi** [comment]
No, not yet. And looks like you're right...
```
$ make install -Bnk | grep 'gcc.* -c'
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c alloc.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c attr.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c context.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c copy.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c encodings.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c equal.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c grammar.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c io.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c lexer.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c match.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c ndtypes.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c parsefuncs.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c parser.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c seq.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c substitute.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c symtable.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c util.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -c values.c
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c alloc.c -o .objs/alloc.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c attr.c -o .objs/attr.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c context.c -o .objs/context.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c copy.c -o .objs/copy.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c encodings.c -o .objs/encodings.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c equal.c -o .objs/equal.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c grammar.c -o .objs/grammar.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c io.c -o .objs/io.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c lexer.c -o .objs/lexer.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c match.c -o .objs/match.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c ndtypes.c -o .objs/ndtypes.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c parsefuncs.c -o .objs/parsefuncs.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c parser.c -o .objs/parser.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c seq.c -o .objs/seq.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c substitute.c -o .objs/substitute.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c symtable.c -o .objs/symtable.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c util.c -o .objs/util.o
gcc -I.. -Wall -Wextra -std=c11 -pedantic -O2 -g -fPIC -c values.c -o .objs/values.o
gcc -dynamiclib -install_name @rpath/libndtypes.0.dylib -compatibility_version 0.2 -current_version 0.2.0 -o libndtypes.0.2.0dev3.dylib .objs/alloc.o .objs/attr.o .objs/context.o .objs/copy.o .objs/encodings.o .objs/equal.o .objs/grammar.o .objs/io.o .objs/lexer.o .objs/match.o .objs/ndtypes.o .objs/parsefuncs.o .objs/parser.o .objs/seq.o .objs/substitute.o .objs/symtable.o .objs/util.o .objs/values.o compat/.objs/bpgrammar.o compat/.objs/bplexer.o compat/.objs/import.o compat/.objs/export.o serialize/.objs/serialize.o serialize/.objs/deserialize.o
gcc -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O2 -c bitmaps.c
gcc -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O2 -c copy.c
gcc -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O2 -c equal.c
gcc -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O2 -c split.c
gcc -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O2 -c xnd.c
gcc -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O2 -fPIC -c bitmaps.c -o .objs/bitmaps.o
gcc -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O2 -fPIC -c copy.c -o .objs/copy.o
gcc -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O2 -fPIC -c equal.c -o .objs/equal.o
gcc -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O2 -fPIC -c split.c -o .objs/split.o
gcc -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O2 -fPIC -c xnd.c -o .objs/xnd.o
gcc -dynamiclib -install_name @rpath/libxnd.0.dylib -undefined dynamic_lookup -compatibility_version 0.2 -current_version 0.2.0 -o libxnd.0.2.0dev3.dylib .objs/bitmaps.o .objs/copy.o .objs/equal.o .objs/split.o .objs/xnd.o
gcc -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -c apply.c
gcc -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -c func.c
gcc -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -c nploops.c
gcc -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -c tbl.c
gcc -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -c thread.c
gcc -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -c xndloops.c
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -Wno-absolute-value -c kernels/unary.c
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -c kernels/binary.c
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -c extending/examples.c -o examples.o
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -c extending/bfloat16.c -o bfloat16.o
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -c extending/graph.c -o graph.o
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -c extending/quaternion.c -o quaternion.o
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -c extending/pdist.c -o pdist.o
gcc -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -fPIC -c apply.c -o .objs/apply.o
gcc -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -fPIC -c func.c -o .objs/func.o
gcc -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -fPIC -c nploops.c -o .objs/nploops.o
gcc -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -fPIC -c tbl.c -o .objs/tbl.o
gcc -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -fPIC -c thread.c -o .objs/thread.o
gcc -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -fPIC -c xndloops.c -o .objs/xndloops.o
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -fPIC -Wno-absolute-value -c kernels/unary.c -o .objs/unary.o
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -fPIC -c kernels/binary.c -o .objs/binary.o
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -fPIC -c extending/examples.c -o .objs/examples.o
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -fPIC -c extending/bfloat16.c -o .objs/bfloat16.o
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -fPIC -c extending/graph.c -o .objs/graph.o
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -fPIC -c extending/quaternion.c -o .objs/quaternion.o
gcc -I. -I.. -I/Users/hameerabbasi/CLionProjects/xnd-all/build/include -Wall -Wextra -std=c11 -pedantic -O3 -fPIC -c extending/pdist.c -o .objs/pdist.o
gcc -dynamiclib -install_name @rpath/libgumath.0.dylib -undefined dynamic_lookup -compatibility_version 0.2 -current_version 0.2.0 -o libgumath.0.2.0dev3.dylib .objs/apply.o .objs/func.o .objs/nploops.o .objs/tbl.o .objs/thread.o .objs/xndloops.o .objs/unary.o .objs/binary.o .objs/examples.o .objs/bfloat16.o .objs/graph.o .objs/quaternion.o .objs/pdist.o
```
